name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Test Action
        id: test-action
        uses: ./
        with:
          sourceRepository: 'hello-world'
          loginToSourceRepository: 'true'
          sourceRepositoryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          sourceRepositoryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
          targetRepository: 'ghcr.io/it-bens/container-registry-sync-action'
          loginToTargetRepository: 'true'
          targetRepositoryUsername: ${{ github.actor }}
          targetRepositoryPassword: ${{ secrets.GITHUB_TOKEN }}
          tags: '*'
          regClientConcurrency: 1

      - name: Prune Copied Images
        uses: vlaurin/action-ghcr-prune@0cf7d39f88546edd31965acba78cdcb0be14d641 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: 'it-bens'
          container: 'container-registry-sync-action'
          dry-run: false
          keep-tags-regexes: 'latest'
          prune-untagged: true
